# Sourced from /etc/loki/local-config.yaml in the grafana/loki:2.9.2 image
auth_enabled: true

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

ingester:
  chunk_encoding: gzip      # default gzip, https://grafana.com/blog/2023/12/28/the-concise-guide-to-loki-how-to-get-the-most-out-of-your-query-performance/
  chunk_target_size: 1536KB  # default: 1536KB ~ 1.5MB

limits_config:
  ingestion_burst_size_mb: 500  # default: 6
  ingestion_rate_mb: 5000 # default 4
  # per_stream_rate_limit: 1024M # default 3MB
  # per_stream_rate_limit_burst: 4096M # default 15MB
  query_timeout: 5m

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  aws:
    s3: http://minioadmin:minioadmin@minio1:9000/
    endpoint: http://minio1:9000/
    bucketnames: loki1
    s3forcepathstyle: true

query_scheduler:
  max_outstanding_requests_per_tenant: 4096

#frontend:
#  max_outstanding_per_tenant: 4096
#query_range:
#  parallelise_shardable_queries: true

ruler:
  alertmanager_url: http://localhost:9093

# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
#
# Statistics help us better understand how Loki is used, and they show us performance
# levels for most users. This helps us prioritize features and documentation.
# For more information on what's sent, look at
# https://github.com/grafana/loki/blob/main/pkg/usagestats/stats.go
# Refer to the buildReport method to see what goes into a report.
#
# If you would like to disable reporting, uncomment the following lines:
analytics:
  reporting_enabled: false
