networks:
  loki:

volumes:
  alloy-data:
  influxdb-data:
  loki-data:
  vector-data:
  secrets:

services:
  autoheal: # https://github.com/willfarrell/docker-autoheal
    image: willfarrell/autoheal:latest
    tty: true
    container_name: autoheal
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  sws: # https://static-web-server.net/getting-started/
    image: joseluisq/static-web-server:2
    ports:
      - "8787:80"
    networks:
      - loki
    volumes:
      - ./docs:/public

  ##############################################
  #              BEGIN GRAFANA ALLOY           #
  ##############################################
  alloy:
    image: grafana/alloy:v1.1.0
    env_file:
      - default.env
      - .env
    command: >
      run --server.http.listen-addr=0.0.0.0:12345
      --storage.path=/var/lib/alloy/data
      /etc/alloy/config.alloy
    ports:
      - "12345:12345"
    networks:
      - loki
    volumes:
      - ./alloy:/etc/alloy
      - alloy-data:/var/lib/alloy/data
      - /var/run/docker.sock:/var/run/docker.sock:rw

  vector:
    build:
      context: .
      dockerfile: vector/Dockerfile
    env_file:
      - default.env
      - .env
    depends_on:
      influxdb:
        condition: service_healthy
      prometheus:
        condition: service_started
    labels:
      - "autoheal=true"
    restart: always
    volumes:
      - ./vector:/etc/vector
      - vector-data:/data_dir
      - ./log_files:/log_files
      - secrets:/secrets
    networks:
      - loki

  loki:
    image: grafana/loki:2.9.2
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki:/etc/loki
      - loki-data:/loki
    ports:
      - "3100:3100"
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    depends_on:
      influxdb:
        condition: service_healthy
    env_file:
      - default.env
      - .env
    entrypoint: /local_bin/entrypoint.sh
    volumes:
      - ./grafana/bin:/local_bin
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - secrets:/secrets
    ports:
      - "3000:3000"
    networks:
      - loki

  ##############################################
  #              BEGIN INFLUXDB                #
  ##############################################
  influxdb:
    image: influxdb:2
    env_file:
      - default.env
      - ./influxdb/influxdb-setup.env
      - .env
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/ls", "/secrets/influxdb_tokens/vector_token"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 5s
    ports:
      - "8086:8086"
    networks:
      - loki
    volumes:
      - ./influxdb:/etc/influxdb2
      - ./influxdb/scripts:/docker-entrypoint-initdb.d
      - influxdb-data:/var/lib/influxdb2
      - secrets:/secrets

  ##############################################
  #              BEGIN PROMETHEUS              #
  ##############################################
  prometheus:
    image: prom/prometheus:v2.45.5
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention.time=2d
      --storage.tsdb.retention.size=20GB
      --web.console.libraries=/usr/share/prometheus/console_libraries
      --web.console.templates=/usr/share/prometheus/consoles/prometheus
      --enable-feature=remote-write-receiver
    ports:
      - "9090:9090"
    networks:
      - loki
