version: '3'

networks:
  loki:

services:
  vector:
    build:
      context: .
      dockerfile: Dockerfile.vector
    env_file:
      - default.env
      - .env
    volumes:
      - ./vector:/etc/vector
      - ./data_dir/vector:/data_dir
      - ./log_files:/log_files
    ports:
      - "8686:8686"
    networks:
      - loki

  loki:
    build:
      context: .
      dockerfile: Dockerfile.loki
    volumes:
      - ./loki:/etc/loki
      - ./data_dir/loki:/loki
    ports:
      - "3100:3100"
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki

  ##############################################
  #              BEGIN INFLUXDB                #
  ##############################################
  influxdb:
    image: influxdb:2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminPassword
      - DOCKER_INFLUXDB_INIT_ORG=test_org
      - DOCKER_INFLUXDB_INIT_BUCKET=test_bucket
    ports:
      - "8086:8086"
    networks:
      - loki
    volumes:
      - ./influxdb:/etc/influxdb2
      - ./data_dir/influxdb:/var/lib/influxdb2
