# https://github.com/grafana/loki
FROM grafana/loki:2.9.2

# Run as non-root. Use GID 1000 to allow access to vault token from vault agent
USER 1000:1000

WORKDIR /

# Copy required files and run necessary preperations here.
COPY loki/config.yaml /etc/loki/

CMD [ "-config.file=/etc/loki/config.yaml" ]
