# See https://github.com/zendesk/docker-images-base for more options.
FROM timberio/vector:0.37.1-debian

# Run as non-root. Use GID 1000 to allow access to vault token from vault agent
USER 1000:1000

# Copy vector configuration
COPY vector/vector.yaml /etc/vector/vector.yaml

CMD [ "--watch-config" ]
