{
 "title": "System Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Loki Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{container_label_service=\"loki\"} / 1000000",
     "legendFormat": "Loki (MB)"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(container_label_service) (irate(container_memory_usage_bytes{container_label_com_docker_compose_project=\"o11y-playground\"}[5m])) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(container_label_service) (irate(container_cpu_usage_seconds_total{container_label_com_docker_compose_project=\"o11y-playground\"}[5m]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Transmit (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(container_label_service) (irate(container_network_transmit_bytes_total{container_label_com_docker_compose_project=\"o11y-playground\"}[5m])) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Received (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(container_label_service) (irate(container_network_receive_bytes_total{container_label_com_docker_compose_project=\"o11y-playground\"}[5m])) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}