{
 "title": "Vector Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Random JSON Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(vector_component_sent_event_bytes_total{component_id=\"random_json\"}[$__rate_interval])",
     "legendFormat": "Sent Bytes"
    },
    {
     "expr": "rate(vector_component_sent_events_total{component_id=\"random_json\"}[$__rate_interval])",
     "legendFormat": "Sent Events"
    }
   ]
  },
  {
   "title": "Blackhole Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(vector_component_sent_event_bytes_total{component_id=\"blackhole\"}[$__rate_interval])",
     "legendFormat": "Sent Bytes"
    },
    {
     "expr": "rate(vector_component_sent_events_total{component_id=\"blackhole\"}[$__rate_interval])",
     "legendFormat": "Sent Events"
    }
   ]
  },
  {
   "title": "Loki Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(vector_component_sent_event_bytes_total{component_id=\"local_loki\"}[$__rate_interval])",
     "legendFormat": "Sent Bytes"
    },
    {
     "expr": "rate(vector_component_sent_events_total{component_id=\"local_loki\"}[$__rate_interval])",
     "legendFormat": "Sent Events"
    }
   ]
  },
  {
   "title": "Vector Log Volume by component (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(vector_component_sent_event_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(vector_component_received_event_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{source=\"vector\"} | json"
    }
   ]
  },
  {
   "title": "Vector Log Volume (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(vector_component_sent_event_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(vector_component_received_event_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate({source=\"vector\"} [$__auto]))",
     "legendFormat": "Vector Log Volume"
    }
   ]
  }
 ]
}