apiVersion: 1
datasources:
- name: Loki
  type: loki
  access: proxy 
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
- name: InfluxDB
  type: influxdb
  url: http://influxdb:8086
  jsonData:
    version: Flux
    organization: test_org
    defaultBucket: ${VECTOR_INFLUXDB_METRICS_BUCKET}
    tlsSkipVerify: true
  secureJsonData:
    token: ${VECTOR_INFLUXDB_TOKEN}
