# https://grafana.com/docs/tempo/latest/configuration/manifest/

server:
  http_listen_port: 3200
  log_level: info
  
distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

compactor:
  compaction:
    block_retention: 48h                # configure total trace retention here

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: linux-microservices
  storage:
    path: /var/tempo/generator/wal
    remote_write:
    - url: http://prometheus:9090/api/v1/write
      send_exemplars: true

storage:
  trace:
    backend: s3
    s3:
      endpoint: minio:9000
      bucket: tempo
      forcepathstyle: true
      enable_dual_stack: false
      # set to false if endpoint is https
      insecure: true
    wal:
      path: /var/tempo/wal         # where to store the wal locally
    local:
      path: /var/tempo/blocks
overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]
